#!/usr/bin/env bash
#
# One-time server setup for automated Let's Encrypt SSL on direct (non-Cloudflare)
# pool domains. Idempotent — safe to re-run. Must run as root.
#
# It:
#   1. installs acme.sh (if missing) and points it at Let's Encrypt,
#   2. writes a shared nginx snippet that mirrors the app's PHP handling so each
#      per-domain TLS vhost (generated by admin/domainmonitor.php) can include it,
#   3. ensures the existing :80 site serves the ACME HTTP-01 challenge path
#      (the app's `location ~ /\.` rule would otherwise 403 `/.well-known/...`),
#   4. installs a root cron job that runs the domain monitor every 5 minutes
#      (live status refresh + auto issue/renew of certificates).
#
# Usage:  sudo bash scripts/setup-domain-ssl.sh [acme-account-email] [webroot]
#
# The email is optional: Let's Encrypt allows registering an account without one
# (you just won't get expiry-reminder emails). Pass "" or omit it to register
# anonymously.
set -euo pipefail

ACME_EMAIL="${1:-${ACME_EMAIL:-}}"
WEBROOT="${2:-/var/www/yaaff}"
CERT_DIR="/etc/yaaff-ssl"
SNIPPET="/etc/nginx/snippets/yaaff-app.conf"
ACME_HOME="/root/.acme.sh"
MONITOR="${WEBROOT}/admin/domainmonitor.php"
LOG="/var/log/yaaff-domains.log"

if [[ "$(id -u)" != "0" ]]; then
  echo "Must run as root." >&2
  exit 1
fi
echo "==> Ensuring acme.sh is installed"
if [[ ! -x "${ACME_HOME}/acme.sh" ]]; then
  if [[ -n "$ACME_EMAIL" ]]; then
    curl -fsSL https://get.acme.sh | sh -s email="${ACME_EMAIL}"
  else
    curl -fsSL https://get.acme.sh | sh
  fi
fi
"${ACME_HOME}/acme.sh" --set-default-ca --server letsencrypt || true
if [[ -n "$ACME_EMAIL" ]]; then
  "${ACME_HOME}/acme.sh" --register-account -m "${ACME_EMAIL}" || true
else
  # Let's Encrypt permits an account with no contact email.
  "${ACME_HOME}/acme.sh" --register-account || true
fi

echo "==> Creating certificate directory ${CERT_DIR}"
mkdir -p "${CERT_DIR}"
chmod 700 "${CERT_DIR}"

echo "==> Detecting PHP-FPM socket"
# Prefer the distro 'alternatives' symlink — it always points at the active PHP.
FPM_SOCK=""
if [[ -S /run/php/php-fpm.sock ]]; then
  FPM_SOCK="/run/php/php-fpm.sock"
fi
# Otherwise read it from the *active* site configs only, skipping commented lines
# (sites-available/default ships a commented `fastcgi_pass ... php7.4` example
# that must not be picked up).
if [[ -z "$FPM_SOCK" ]]; then
  FPM_SOCK="$(grep -rhE 'fastcgi_pass[[:space:]]+unix:' /etc/nginx/sites-enabled /etc/nginx/conf.d 2>/dev/null \
    | grep -vE '^[[:space:]]*#' \
    | sed -E 's/.*unix:([^;]+);?.*/\1/' | tr -d ' ' | head -1)"
fi
# Last resort: the first live socket under /run/php.
if [[ -z "$FPM_SOCK" ]]; then
  FPM_SOCK="$(ls /run/php/*-fpm.sock 2>/dev/null | head -1)"
fi
FPM_SOCK="${FPM_SOCK:-/run/php/php-fpm.sock}"
echo "    using ${FPM_SOCK}"

echo "==> Writing nginx app snippet ${SNIPPET}"
mkdir -p "$(dirname "${SNIPPET}")"
cat > "${SNIPPET}" <<NGINX
# Managed by YaAff — shared app handling for generated TLS vhosts. Do not edit.
index index.php index.html;
client_max_body_size 64m;

location ~ ^/(db|logs)(/|\$) { deny all; }
location ~ /\. { deny all; }
location = /composer.json { deny all; }
location = /composer.lock { deny all; }
location = /settings.php { deny all; }
location = /phpunit.xml { deny all; }

location / {
    try_files \$uri \$uri/ /index.php?\$query_string;
}

location ~ \.php\$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:${FPM_SOCK};
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
}
NGINX

echo "==> Ensuring the :80 site serves the ACME HTTP-01 challenge"
# acme.sh uses webroot HTTP-01 over the existing :80 site. That site denies any
# dotfile path (`location ~ /\.`), which also blocks `/.well-known/acme-challenge`
# and makes Let's Encrypt return 403. Inject a higher-priority `^~` location
# (prefix match wins over regex) into the enabled :80 server block so challenges
# are served as plain files. Idempotent and guarded by a marker.
ensure_acme_challenge_on_80() {
  local target
  target="$(grep -lE 'listen([[:space:]]+[^;]*)?[[:space:]]80([[:space:];]|$)' \
    /etc/nginx/sites-enabled/* /etc/nginx/conf.d/*.conf 2>/dev/null | head -1)"
  if [[ -z "$target" ]]; then
    echo "    WARNING: no :80 server block found; add an ACME challenge location" >&2
    echo "    manually if issuance returns 403." >&2
    return 0
  fi
  if grep -q 'well-known/acme-challenge' "$target"; then
    echo "    already present in ${target}"
    return 0
  fi
  cp "$target" "${target}.yaaff-bak.$(date +%s)"
  WEBROOT="$WEBROOT" TARGET="$target" python3 - <<'PY'
import os, re
p = os.environ["TARGET"]; webroot = os.environ["WEBROOT"]
s = open(p).read()
block = (
    "    # Managed by YaAff: allow ACME HTTP-01 (beats the dotfile deny via ^~).\n"
    "    location ^~ /.well-known/acme-challenge/ {\n"
    '        default_type "text/plain";\n'
    f"        root {webroot};\n"
    "        try_files $uri =404;\n"
    "    }\n"
)
# Insert right after the first `server {` opening brace.
m = re.search(r'server\s*\{[^\n]*\n', s)
if m:
    s = s[:m.end()] + "\n" + block + s[m.end():]
    open(p, "w").write(s)
    print("    injected ACME challenge location into " + p)
else:
    raise SystemExit("could not locate a server block in " + p)
PY
}
ensure_acme_challenge_on_80

echo "==> Validating nginx config"
nginx -t
nginx -s reload

echo "==> Installing monitor cron (every 5 minutes)"
CRON_LINE="*/5 * * * * php ${MONITOR} >> ${LOG} 2>&1"
( crontab -l 2>/dev/null | grep -v -F "${MONITOR}" ; echo "${CRON_LINE}" ) | crontab -
touch "${LOG}"

echo "==> Done. Direct domains pointing at this server will get Let's Encrypt"
echo "    certificates automatically within ~5 minutes. Cloudflare-fronted"
echo "    domains are fixed via the Cloudflare API by the same monitor."
