#!/usr/bin/env bash
#
# One-time server setup for automated Let's Encrypt SSL on direct (non-Cloudflare)
# pool domains. Idempotent — safe to re-run. Must run as root.
#
# It:
#   1. installs acme.sh (if missing) and points it at Let's Encrypt,
#   2. writes a shared nginx snippet that mirrors the app's PHP handling so each
#      per-domain TLS vhost (generated by admin/domainmonitor.php) can include it,
#   3. installs a root cron job that runs the domain monitor every 5 minutes
#      (live status refresh + auto issue/renew of certificates).
#
# HTTP-01 validation is served over the existing :80 site from the webroot, so no
# extra nginx location is required (try_files already serves .well-known files).
#
# Usage:  sudo bash scripts/setup-domain-ssl.sh you@example.com [webroot]
set -euo pipefail

ACME_EMAIL="${1:-${ACME_EMAIL:-}}"
WEBROOT="${2:-/var/www/yaaff}"
CERT_DIR="/etc/yaaff-ssl"
SNIPPET="/etc/nginx/snippets/yaaff-app.conf"
ACME_HOME="/root/.acme.sh"
MONITOR="${WEBROOT}/admin/domainmonitor.php"
LOG="/var/log/yaaff-domains.log"

if [[ "$(id -u)" != "0" ]]; then
  echo "Must run as root." >&2
  exit 1
fi
if [[ -z "$ACME_EMAIL" ]]; then
  echo "Usage: $0 <acme-account-email> [webroot]" >&2
  exit 1
fi

echo "==> Ensuring acme.sh is installed"
if [[ ! -x "${ACME_HOME}/acme.sh" ]]; then
  curl -fsSL https://get.acme.sh | sh -s email="${ACME_EMAIL}"
fi
"${ACME_HOME}/acme.sh" --set-default-ca --server letsencrypt || true
"${ACME_HOME}/acme.sh" --register-account -m "${ACME_EMAIL}" || true

echo "==> Creating certificate directory ${CERT_DIR}"
mkdir -p "${CERT_DIR}"
chmod 700 "${CERT_DIR}"

echo "==> Detecting PHP-FPM socket"
FPM_SOCK="$(grep -rhoE 'fastcgi_pass[[:space:]]+unix:[^;]+' /etc/nginx 2>/dev/null | head -1 | sed -E 's/.*unix:([^;]+)/\1/' | tr -d ' ')"
FPM_SOCK="${FPM_SOCK:-/run/php/php8.3-fpm.sock}"
echo "    using ${FPM_SOCK}"

echo "==> Writing nginx app snippet ${SNIPPET}"
mkdir -p "$(dirname "${SNIPPET}")"
cat > "${SNIPPET}" <<NGINX
# Managed by YaAff — shared app handling for generated TLS vhosts. Do not edit.
index index.php index.html;
client_max_body_size 64m;

location ~ ^/(db|logs)(/|\$) { deny all; }
location ~ /\. { deny all; }
location = /composer.json { deny all; }
location = /composer.lock { deny all; }
location = /settings.php { deny all; }
location = /phpunit.xml { deny all; }

location / {
    try_files \$uri \$uri/ /index.php?\$query_string;
}

location ~ \.php\$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:${FPM_SOCK};
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
}
NGINX

echo "==> Validating nginx config"
nginx -t
nginx -s reload

echo "==> Installing monitor cron (every 5 minutes)"
CRON_LINE="*/5 * * * * php ${MONITOR} >> ${LOG} 2>&1"
( crontab -l 2>/dev/null | grep -v -F "${MONITOR}" ; echo "${CRON_LINE}" ) | crontab -
touch "${LOG}"

echo "==> Done. Direct domains pointing at this server will get Let's Encrypt"
echo "    certificates automatically within ~5 minutes. Cloudflare-fronted"
echo "    domains are fixed via the Cloudflare API by the same monitor."
